---
- name: get facts about the newly created cfn network stack
  cloudformation_facts:
    stack_name: "ansible-cfn-demo-network"
  register: cfn_network_stack_facts

- name: create a stack, pass in the template via an URL
  vars:
    network_output: "{{ cfn_network_stack_facts.ansible_facts.cloudformation['ansible-cfn-demo-network'].stack_outputs }}"
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ lookup('env','AWS_REGION') }}"
    disable_rollback: false
    template_url: "{{ lookup('env','TEMPLATE_URL') }}"
    template_parameters:
      VpcId: "{{ network_output.VPC }}"
      Subnets: "{{ network_output.PublicSubnets }}"
      InstanceType: "{{  lookup('env','INSTANCE_TYPE') }}"
      KeyName: "{{  lookup('env','KEY_NAME') }}"
      SSHLocation: "{{ lookup('env','SSH_LOCATION') }}"
      TagName: "{{  lookup('env','TAG_NAME') }}"
      TagGroup: "{{  lookup('env','TAG_GROUP') }}"
      TagEnv: "{{ lookup('env','TAG_ENVIRONMENT') }}"
    tags:
      Stack: "{{ stack_name }}"