version: 0.2

env:
  variables:
    TEMPLATE_URL: "https://s3.amazonaws.com/gaystafford_cloud_formation/cf_demo/network-stack.template"
    AWS_REGION: 'us-east-1'
    TAG_ENVIRONMENT: "ansible-cfn-demo"
  parameter-store:
    vpc_cidr: "/ansible_demo/vpc_cidr"
    public_subnet_1_cidr: "/ansible_demo/public_subnet_1_cidr"
    public_subnet_2_cidr: "/ansible_demo/public_subnet_2_cidr"
    private_subnet_1_cidr: "/ansible_demo/private_subnet_1_cidr"
    private_subnet_2_cidr: "/ansible_demo/private_subnet_2_cidr"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt -q
  build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml playbooks/10_cfn_network.yml --tags create -vvv
  post_build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml roles/cfn_network/tests/test.yml