version: 0.2

env:
  parameter-store:
    ANSIBLE_PRIVATE_KEY: "/ansible_demo/ansible_private_key"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install -r requirements.txt -q
      - mkdir -p ~/.ssh
      - echo "$ANSIBLE_PRIVATE_KEY" > ~/.ssh/ansible
      - chmod 600 ~/.ssh/ansible
  pre_build:
    commands:
      - ansible-inventory -i inventories/aws_ec2.yml --graph
      - ansible-playbook -i inventories/aws_ec2.yml roles/cfn_compute/tests/test.yml
  build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml playbooks/30_web_config.yml -vvv
  post_build:
    commands:
      - ansible-playbook -i inventories/aws_ec2.yml roles/httpd/tests/test.yml